name: Build and Test tcping

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-arm64:
    runs-on: macos-latest
    steps:
      # checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # install pkg
      - name: Install Dependencies
        run: |
          df -h
          brew install telegram-desktop mpv
          df -h
